name: Automated Release PR

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version Number'
        required: true

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    # Add steps for committing and pushing any changes you want in the release

    - name: Create Release PR
      env: 
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: | 
        gh pr create --title "Release ${{ github.event.inputs.version }}" --body "Release ${{ github.event.inputs.version }}"
        gh pr create -b "main" -t "develop"
    


    # Add steps for automatically merging the PR, possibly waiting for checks
    # You may need to use GitHub API or another Action for merging
