name: Create and Merge PR with GitHub CLI

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version Number'
        required: true

jobs:
  create-and-merge-pr:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Create Release Branch
      run: |
        git checkout -b release-${{ github.event.inputs.version }} develop
        git push origin release-${{ github.event.inputs.version }}

    # Add steps for committing and pushing any changes you want in the release

    - name: Create Pull Request
      env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        PR_URL=$(gh pr create --base main --head release-${{ github.event.inputs.version }} --title "Release ${{ github.event.inputs.version }}" --body "Release PR for version ${{ github.event.inputs.version }}" --label "release")
        echo "Pull Request URL: $PR_URL"

    - name: Automatically Merge the Pull Request
      run: |
        PR_NUMBER=$(basename $PR_URL)
        gh pr merge $PR_NUMBER --auto --squash

    # Optional cleanup step
    - name: Delete Release Branch
      run: git push origin --delete release-${{ github.event.inputs.version }}
