name: Automated Release PR

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version Number'
        required: true

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    # Add steps for committing and pushing any changes you want in the release

    - name: Create Pull Request
      id: create_pr
      uses: repo-sync/pull-request@v2
      with:
        INPUT_GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        INPUT_PR_TITLE: "Release ${{ github.event.inputs.version }}"
        INPUT_PR_BODY: "Release PR for version ${{ github.event.inputs.version }}"
        INPUT_PR_BASE: "master"
        INPUT_PR_HEAD: "develop"


    # Add steps for automatically merging the PR, possibly waiting for checks
    # You may need to use GitHub API or another Action for merging
