name: Automated Release PR

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version Number'
        required: true

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Create Release Branch
      run: git checkout -b release-${{ github.event.inputs.version }} develop

    # Add steps for committing and pushing any changes you want in the release

    - name: Create Pull Request
      id: create_pr
      uses: poorva17/create-pr-action@main
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        pr_title: "Release ${{ github.event.inputs.version }}"
        pr_body: "Release PR for version ${{ github.event.inputs.version }}"
        pr_base: "master"
        pr_head: "de"

    - name: Add 'release' Label to PR
      uses: actions/github-script@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        script: |
          github.issues.addLabels({
            owner: context.repo.owner,
            repo: context.repo.repo,
            issue_number: ${{ steps.create_pr.outputs.pr_number }},
            labels: ['release']
          })

    # Add steps for automatically merging the PR, possibly waiting for checks
    # You may need to use GitHub API or another Action for merging

    # Optional cleanup step
    - name: Delete Release Branch
      run: git push origin --delete release-${{ github.event.inputs.version }}
